# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anthologion Devlog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    [Anthologion](https://anthologion.faith/): The one stop shop for liturgical texts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anthologion.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  anthologion

# Build settings
markdown: kramdown
